// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXXStcSswKZkrHF1y0uoc3LBaFstBNh38',
    appId: '1:403113883404:web:50f0e39d25327e78c67b29',
    messagingSenderId: '403113883404',
    projectId: 'fire5-1fd51',
    authDomain: 'fire5-1fd51.firebaseapp.com',
    storageBucket: 'fire5-1fd51.appspot.com',
    measurementId: 'G-FVQPV0MRW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGkj8Fr1fwNahDd8XeRdJyVc-kRZwpB2I',
    appId: '1:403113883404:android:73ef60e6df1f9c05c67b29',
    messagingSenderId: '403113883404',
    projectId: 'fire5-1fd51',
    storageBucket: 'fire5-1fd51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw-EE8meqZVPPX7X6PdxGhprI1lpKc3yM',
    appId: '1:403113883404:ios:d42130c88006993ec67b29',
    messagingSenderId: '403113883404',
    projectId: 'fire5-1fd51',
    storageBucket: 'fire5-1fd51.appspot.com',
    iosBundleId: 'com.example.fire5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw-EE8meqZVPPX7X6PdxGhprI1lpKc3yM',
    appId: '1:403113883404:ios:d42130c88006993ec67b29',
    messagingSenderId: '403113883404',
    projectId: 'fire5-1fd51',
    storageBucket: 'fire5-1fd51.appspot.com',
    iosBundleId: 'com.example.fire5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXXStcSswKZkrHF1y0uoc3LBaFstBNh38',
    appId: '1:403113883404:web:89ff3fe7b496e48dc67b29',
    messagingSenderId: '403113883404',
    projectId: 'fire5-1fd51',
    authDomain: 'fire5-1fd51.firebaseapp.com',
    storageBucket: 'fire5-1fd51.appspot.com',
    measurementId: 'G-H85SYZ1F64',
  );
}
